export { AdminPage } from './admin'
export { ErrorPage } from './error'
export { Home } from './home'
export { Auth } from './auth'
export { TicketDetail } from './ticket/[id]'
export { Profile } from './profile'
export { Catalog } from './catalog'
